service: SimpleQuery
frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'sa-east-1'}
  runtime: python2.7
  deploymentBucket:
    name: lambda.${self:provider.stage}.deploys

functions:
  SimpleQuery:
    name: ${self:service}
    description: "Search items on the database"
    handler: exec.main
    memory: 128
    timeout: 10
    environment:
      MYSQL_HOST: ${file(../env.yml):${self:provider.stage}.MYSQL_HOST}
      MYSQL_USER: ${file(../env.yml):${self:provider.stage}.MYSQL_USER}
      MYSQL_PASS: ${file(../env.yml):${self:provider.stage}.MYSQL_PASS}
      MYSQL_DB: ${file(../env.yml):${self:provider.stage}.MYSQL_DB}
    events:
      - http:
          path: item/list
          method: GET
#      - cloudwatchLog:
#          logGroup: /aws/lambda
    cors:
      - enabled: true

plugins:
  - serverless-plugin-simulate

custom:
  customDomain:
    domainName: "test"